services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      UPLOAD_DIR: /app/uploads
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /mnt/gluster-test:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"

volumes:
  postgres_data:
